INSERT INTO `music`.`persona` (`nombre`) VALUES ('Antonio Cortés');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Rafael Sánchez');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Luis Bolín');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Mario Martínez');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ben Hoffnung');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Robert Atchison');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Roland Roberts');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ian Rowbotham');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Erica Simpson');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Noel Langley');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Dennis Rollins');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Scott Garland');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Mario Ricci');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ingrid Schroeder');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Geoff Dunn');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Geoff Hunt');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('John Palmer');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Yan Memnis');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Gary Moore');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ian Taylor');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Steve Fitzmaurice');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Noel Harris');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Stuart Day');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Marcus Draws');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Greg Muden');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Hayden Bendall');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Don Airey');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Williams');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Jimmy Rodgers');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Johnny \"Guitar\" Watson');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Maxwell Davies');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Saul Bihari');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Dan Malone');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('George Harrison');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Rush');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Peter Green');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Mick Weaver');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Andy Pyle');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Graham Walker');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Albert King');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Raoul D\'Olivera');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Frank Mead');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Nick Pentelow');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Nick Payn');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Nicky Hopkins');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Gavin Wright');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Bob Daisley');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Brian Downey');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Stuart Brooks');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Andrew Hamilton');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Martin Drover');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Gregg Jackman');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Peter Hodgson');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Robin Barclay');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Matt Lane');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ed Goldberg');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Ellen Fitton');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Alec Firla');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Andy Baker');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Tommy Eyre');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('B. B. King');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Albert Collins');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Hudson Whittaker');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('John Mayall');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('D. Bennett');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Milton Campbell');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Tommy Eyre');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Will Lee');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Jonnhy B. Gaydon');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Anton Fig');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Andrew Love');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Wayne Jackson');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Carol Kenyon');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Linda Taylor');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Richard Morgan');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Mike Howlett');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Zatu');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Acción Sánchez');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Little Pepe');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Green Valley');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Shabu');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Mala Juntera');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Fyahboy');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Juaninacka');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Alberto Gambino');
INSERT INTO `music`.`persona` (`nombre`) VALUES ('Kriss');
