INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('13', 'Coros');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('14', 'Coros');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('15', 'Batería');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('16', 'Ingeniero sonido y mezclas');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('17', 'Ingeniero sonido');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('18', 'Asistente ingeniero');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('26', 'Ingeniero');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('55', 'Ingeniero');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('56', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('57', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('58', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('59', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('60', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('61', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('21', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('22', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('23', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('24', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('25', 'Asistente');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('20', 'Ingeniero');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('27', 'Director de cuerda');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('46', 'Director de cuerda');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('81', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('82', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('83', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('84', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('85', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('86', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('87', 'Colaborador');
INSERT INTO `music`.`otro` (`idpersona`, `papel`) VALUES ('88', 'Colaborador');
