INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Piano');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Teclado');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Cuerda');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Violín');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Viola');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Violonchelo');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Metal');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Trompeta');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Trombón');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Saxo tenor');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Horns');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Guitarra/Vocal');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Bajo');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Tambor');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Hammond Organ');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Alto Sax');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Tenor Sax');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Baritone Sax');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Harmónica');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Alto Sax');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Piano Eléctrico');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Slide and Rhythm Guitar');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Saxes');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Backing Vocals');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Oboe');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Guitarra');
INSERT INTO `music`.`instrumento` (`nombre`) VALUES ('Brass');